#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
 # schedule:
  #  - cron: 0 20 * * *
      
  push:
    branches: 
     - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h
          
      - name: soft
        run: |
          cd package/lean
          mkdir openwrt-package
          cd openwrt-package
          git clone https://github.com/frainzy1477/luci-app-clash.git
          # git clone https://github.com/hong0980/luci-app-passwall.git
          git clone https://github.com/rosywrt/luci-theme-rosy.git
          git clone https://github.com/tzxiaozhen88/luci-app-koolproxyR.git
          git clone https://github.com/Aslin-Ameng/luci-app-access-control.git

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
 
      - name: Generate configuration file
        run: make defconfig

          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_PACKAGE_grub2-efi=y
          CONFIG_EFI_IMAGES=y
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_TARGET_KERNEL_PARTSIZE=16
          CONFIG_TARGET_ROOTFS_PARTSIZE=160
          CONFIG_PACKAGE_luci-theme-argon is not set
          CONFIG_PACKAGE_luci-theme-material is not set
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_dnsmasq_full_auth=y
          CONFIG_PACKAGE_dnsmasq_full_conntrack=y
          CONFIG_PACKAGE_dnsmasq_full_dnssec=y
          CONFIG_PACKAGE_ddns-scripts_cloudflare.com-v4=y
          CONFIG_PACKAGE_ddns-scripts_freedns_42_pl=y
          CONFIG_PACKAGE_ddns-scripts_godaddy.com-v1=y
          CONFIG_PACKAGE_ddns-scripts_no-ip_com=y
          CONFIG_PACKAGE_ddns-scripts_nsupdate=y
          CONFIG_PACKAGE_ddns-scripts_route53-v1=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_wget=y
          CONFIG_PACKAGE_kmod-kvm-amd=y
          CONFIG_PACKAGE_kmod-kvm-intel=y
          CONFIG_PACKAGE_kmod-kvm-x86=y
          CONFIG_OPENSSL_ENGINE_CRYPTO=y
          CONFIG_OPENSSL_ENGINE_DIGEST=y
          CONFIG_OPENSSL_WITH_CAMELLIA=y
          CONFIG_OPENSSL_WITH_COMPRESSION=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
          CONFIG_OPENSSL_WITH_GOST=y
          CONFIG_OPENSSL_WITH_IDEA=y
          CONFIG_OPENSSL_WITH_MDC2=y
          CONFIG_OPENSSL_WITH_RFC3779=y
          CONFIG_OPENSSL_WITH_SEED=y
          CONFIG_OPENSSL_WITH_WHIRLPOOL=y
          CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
          CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
          CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
          CONFIG_OPENVPN_openssl_ENABLE_LZO=y
          CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
          CONFIG_OPENVPN_openssl_ENABLE_PF=y
          CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
          CONFIG_OPENVPN_openssl_ENABLE_SERVER=y
          CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
          CONFIG_KERNEL_BUILD_USER="Qoo"
          CONFIG_GRUB_TITLE="OpenWRT AutoBuild by Qoo"
          CONFIG_PACKAGE_kmod-usb-ohci is not set
          CONFIG_PACKAGE_kmod-usb-ohci-pci is not set
          CONFIG_PACKAGE_kmod-usb-storage-uas is not set
          CONFIG_PACKAGE_kmod-usb-uhci is not set
          CONFIG_PACKAGE_kmod-usb2 is not set
          CONFIG_PACKAGE_kmod-usb2-pci is not set
          CONFIG_PACKAGE_kmod-usb3 is not set
          CONFIG_PACKAGE_luci-app-accesscontrol=y
          CONFIG_PACKAGE_luci-app-adblock is not set
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-advanced-reboot is not set
          CONFIG_PACKAGE_luci-app-ahcp is not set
          CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-aria2 is not set
          CONFIG_PACKAGE_luci-app-arpbind=y
          CONFIG_PACKAGE_luci-app-asterisk is not set
          CONFIG_PACKAGE_luci-app-attendedsysupgrade is not set
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-baidupcs-web is not set
          CONFIG_PACKAGE_luci-app-bcp38 is not set
          CONFIG_PACKAGE_luci-app-bird4 is not set
          CONFIG_PACKAGE_luci-app-bird6 is not set
          CONFIG_PACKAGE_luci-app-bmx6 is not set
          CONFIG_PACKAGE_luci-app-bmx7 is not set
          CONFIG_PACKAGE_luci-app-cjdns is not set
          CONFIG_PACKAGE_luci-app-clamav is not set
          CONFIG_PACKAGE_luci-app-commands is not set
          CONFIG_PACKAGE_luci-app-cshark is not set
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-clash=y
          CONFIG_PACKAGE_luci-app-diag-core is not set
          CONFIG_PACKAGE_luci-app-dnscrypt-proxy is not set
          CONFIG_PACKAGE_luci-app-dnsforwarder is not set
          CONFIG_PACKAGE_luci-app-dnspod is not ser
          CONFIG_PACKAGE_luci-app-docker is not set
          CONFIG_PACKAGE_luci-app-dump1090 is not set
          CONFIG_PACKAGE_luci-app-dynapoint is not set
          CONFIG_PACKAGE_luci-app-e2guardian is not set
          CONFIG_PACKAGE_luci-app-familycloud is not set
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload is not set
          CONFIG_PACKAGE_luci-app-freifunk-diagnostics is not set
          CONFIG_PACKAGE_luci-app-freifunk-policyrouting is not set
          CONFIG_PACKAGE_luci-app-freifunk-widgets is not set
          CONFIG_PACKAGE_luci-app-frpc is not set
          CONFIG_PACKAGE_luci-app-fwknopd is not set
          CONFIG_PACKAGE_luci-app-guest-wifi is not set
          CONFIG_PACKAGE_luci-app-haproxy-tcp is not set
          CONFIG_PACKAGE_luci-app-hd-idle is not set
          CONFIG_PACKAGE_luci-app-hnet is not set
          CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          CONFIG_PACKAGE_luci-app-kodexplorer is not set
          CONFIG_PACKAGE_luci-app-lxc is not set
          CONFIG_PACKAGE_luci-app-meshwizard is not set
          CONFIG_PACKAGE_luci-app-minidlna is not set
          CONFIG_PACKAGE_luci-app-mjpg-streamer is not set
          CONFIG_PACKAGE_luci-app-mtwifi is not set
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-n2n_v2 is not set
          CONFIG_PACKAGE_luci-app-netdata is not set
          CONFIG_PACKAGE_luci-app-nft-qos is not set
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-noddos is not set
          CONFIG_PACKAGE_luci-app-nps is not set
          CONFIG_PACKAGE_luci-app-ntpc is not set
          CONFIG_PACKAGE_luci-app-ocserv is not set
          CONFIG_PACKAGE_luci-app-olsr is not set
          CONFIG_PACKAGE_luci-app-olsr-services is not set
          CONFIG_PACKAGE_luci-app-olsr-viz is not set
          CONFIG_PACKAGE_luci-app-openvpn is not set
          CONFIG_PACKAGE_luci-app-openvpn-server is not set
          CONFIG_PACKAGE_luci-app-p910nd is not set
          CONFIG_PACKAGE_luci-app-pagekitec is not set
          CONFIG_PACKAGE_luci-app-polipo is not set
          CONFIG_PACKAGE_luci-app-pppoe-relay is not set
          CONFIG_PACKAGE_luci-app-pptp-server is not set
          CONFIG_PACKAGE_luci-app-privoxy is not set
          CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-qos is not set
          CONFIG_PACKAGE_luci-app-radicale is not set
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-rp-pppoe-server is not set
          CONFIG_PACKAGE_luci-app-samba is not set
          CONFIG_PACKAGE_luci-app-samba4 is not set
          CONFIG_PACKAGE_luci-app-shadowsocks-libev is not set
          CONFIG_PACKAGE_luci-app-shairplay is not set
          CONFIG_PACKAGE_luci-app-siitwizard is not set
          CONFIG_PACKAGE_luci-app-simple-adblock is not set
          CONFIG_PACKAGE_luci-app-softethervpn is not set
          CONFIG_PACKAGE_luci-app-splash is not set
          CONFIG_PACKAGE_luci-app-sqm is not set
          CONFIG_PACKAGE_luci-app-squid is not set
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssrserver-python is not set
          CONFIG_PACKAGE_luci-i18n-ssrserver-python-zh-cn is not set
          CONFIG_PACKAGE_luci-app-statistics is not set
          CONFIG_PACKAGE_luci-app-syncdial is not set
          CONFIG_PACKAGE_luci-app-tinyproxy is not set
          CONFIG_PACKAGE_luci-app-transmission is not set
          CONFIG_PACKAGE_luci-app-travelmate is not set
          CONFIG_PACKAGE_luci-app-udpxy is not set
          CONFIG_PACKAGE_luci-app-uhttpd is not set
          CONFIG_PACKAGE_luci-app-unblockmusic is not set
          CONFIG_PACKAGE_luci-app-unbound is not set
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-usb-printer is not set
          CONFIG_PACKAGE_luci-app-v2ray-server is not set
          CONFIG_PACKAGE_luci-app-verysync is not set
          CONFIG_PACKAGE_luci-app-vlmcsd is not set
          CONFIG_PACKAGE_luci-app-vnstat is not set
          CONFIG_PACKAGE_luci-app-vpnbypass is not set
          CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-app-watchcat is not set
          CONFIG_PACKAGE_luci-app-webadmin is not set
          CONFIG_PACKAGE_luci-app-wifischedule is not set
          CONFIG_PACKAGE_luci-app-wireguard is not set
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-wrtbwmon is not set
          CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-theme-rosy=y
          EOF
      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
